### PR TITLE
Don't catch the Guzzle Exceptions

### PR DESCRIPTION
**Pull request by thomaschaaf**
Before the use statement for the ClientException was missing. But also catching the error and just echoing something is not good practice as we can't catch the error anymore.

### CODE REVIEW

**Comment by keradus** [comment]
That's really nice change!
In fact, It's needed for me.

Is there some plan to merge this?

**Comment by keradus** [comment]
cc @cachrisman

**Comment by keradus** [comment]
anyone ?

**Comment by thomaschaaf** [comment]
You can just set it as a composer source. :) Then you can use it until someday they merge this.

**Comment by keradus** [comment]
I know how to handle it on my side, but that's not long-term solution :(

**Comment by keradus** [comment]
It would be great to have it finally merged ;)

**Comment by cachrisman** [comment]
just to be clear, because `http_errors` is set to `false` in the guzzle client, the only exceptions that Guzzle will throw will be `GuzzleHttp\Exception\RequestException` or its sub-exceptions, `GuzzleHttp\Exception\ConnectException` and `GuzzleHttp\Exception\TooManyRedirectsException`. `GuzzleHttp\Exception\ClientException` (aka 400 errors) and `GuzzleHttp\Exception\ServerException` (aka 500 errors) are returned as responses to a request.

**Pull request merged**
