### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by jonbaldie**
When I first used this repo it worked excellently but it's very hard to navigate, because it's all in one file. Now they're split out and using the PSR-4 autoloading standard.

No changes to functionality.

Up to you guys if you want this refactor in the main repo.

### CODE REVIEW

**Comment by andreybolonin** [comment]
Maybe something simple that this PR - https://github.com/plivo/plivo-php/pull/39 :)

**Comment by jonbaldie** [comment]
I can add those changes in my branch if you want?

**Comment by jonbaldie** [comment]
Actually I'm not sure I understand your comment lol

**Comment by jamesgraham** [comment]
Is there any hope of this getting merged? Otherwise we are going to maintain a fork of it

**Comment by jonbaldie** [comment]
Yeah it looks like they're not going to respond any time soon. Let's just maintain the fork

November 10 2016 10:57 AM, "James Graham"  wrote:
	Is there any hope of this getting merged? Otherwise we are going to maintain a fork of it

**Comment by keradus** [comment]
A lot of good work here. Sadly, repo looks dead and Plivo company don't give a... .

**Pull request closed without merging**
