### PR TITLE
Composer + PSR4 + dotenv

### PR DESCRIPTION
**Pull request by Narno**

### CODE REVIEW

**Comment by Narno** [comment]
Um, I missed the "dev" branch...

**Comment by Narno** [comment]
@tamiel @tsudot do you think it's interesting that I port my work on PSR4 + dotenv to the "dev" branch?

**Comment by tsudot** [comment]
@Narno The dev branch is still not stable. I'll take a look at this PR. We could really use some test cases though. At least something for us to get started :)

**Comment by keradus** [comment]
Any news on that?

**Comment by keradus** [comment]
:(

**Comment by Narno** [comment]
Sorry @keradus, not enough time :/

**Pull request closed without merging**
